// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package g16_tda593;

import simbad.sim.EnvironmentDescription;

/************************************************************/
/**
 * 
 */
public abstract class Area {
	
	private int pointsRewarded;
	
	public Area(Span span, int reward) {
		this.span = span;
		this.pointsRewarded = reward;
	}
	
	public Area(float x1, float y1, float x2, float y2, int reward) {
		this.span = new Span(x1,y1,x2,y2);
		this.pointsRewarded = reward;
	}
	
	public int getReward() {
		return pointsRewarded;
	}

	/**
	 * 
	 */
	private EnvironmentDescription e = new EnvironmentDescription();
	/**
	 * 
	 */
	private Span span;

	/**
	 * 
	 * @return 
	 */
	public EnvironmentDescription getEnvironment() {
		return e;
	}

	/**
	 * 
	 * @return 
	 */
	public Span getSpan() {
		return span;
	}
	
	public boolean containsRobot(RobotAvatar r) {
		//System.out.println("Position of robot is: X: " + r.getPosition().getX() + " Z: " + r.getPosition().getZ());
		//System.out.println("Span is between " + span.x1 + " to " + span.x2 + " in X direction");
		//System.out.println("Span is between " + span.y1 + " to " + span.y2 + " in Y direction");
		if((r.getPosition().getX() >= span.x1 && r.getPosition().getX() <= span.x2) &&
				(r.getPosition().getZ() >= span.y1 && r.getPosition().getZ() <= span.y2)){
			System.out.println("There is a motherfuckin robot in here");
			return true;
		}
		return false;
	}
};
