// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package g16_tda593;

import simbad.sim.EnvironmentDescription;

/************************************************************/
/**
 * 
 */
public abstract class Area {
	
	private int pointsRewarded;
	
	public Area(Span span, int reward) {
		this.span = span;
		this.pointsRewarded = reward;
	}
	
	public Area(float x1, float x2, float y1, float y2, int reward) {
		this.span = new Span(x1,x2,y1,y2);
		this.pointsRewarded = reward;
	}
	
	public int getReward() {
		return pointsRewarded;
	}

	/**
	 * 
	 */
	private EnvironmentDescription e = new EnvironmentDescription();
	/**
	 * 
	 */
	private Span span;

	/**
	 * 
	 * @return 
	 */
	public EnvironmentDescription getEnvironment() {
		return e;
	}

	/**
	 * 
	 * @return 
	 */
	public Span getSpan() {
		return span;
	}
	
	public boolean containsRobot(RobotAvatar r) {
		if(r.getPosition().getX() <= span.y2 &&
				r.getPosition().getZ() <= span.x2 &&
				r.getPosition().getZ() >= span.x1 &&
				r.getPosition().getX() >= span.y1) {
			return true;
		}
		return false;
	}
};
