package g16_tda593;

import simbad.sim.Boundary;
import simbad.sim.EnvironmentDescription;
import simbad.sim.HorizontalBoundary;
import simbad.sim.HorizontalWall;
import simbad.sim.VerticalBoundary;
import simbad.sim.VerticalWall;

// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
public class AssignmentRoom3 {
	public Area makeRoom() {
		EnvironmentDescription e = new EnvironmentDescription ();
		Boundary w1 = new HorizontalBoundary(-7.0f, -7.0f, 7.0f, e);
		e.add(w1);
		Boundary w2 = new HorizontalBoundary(7.0f, -7.0f, 7.0f, e);
		e.add(w2);
		Boundary w3 = new VerticalBoundary(7.0f, -7.0f, 7.0f, e);
		e.add(w3);
		Boundary w4 = new VerticalBoundary(-7.0f, -7.0f, 7.0f, e);
		e.add(w4);
		
		//Horizontal walls
		HorizontalWall w5 = new HorizontalWall(0f, 3.5f, 5.0f, e);
		e.add(w5);
		HorizontalWall w6 = new HorizontalWall(0f, -3.5f, -5.0f, e);
		e.add(w6);
		HorizontalWall w7 = new HorizontalWall(0f, 1.25f, -1.25f, e);
		e.add(w7);
		
		//Left wall
		HorizontalWall w8 = new HorizontalWall(5f, 3.5f, 5.0f, e);
		e.add(w8);
		HorizontalWall w9 = new HorizontalWall(5f, -3.5f, -5.0f, e);
		e.add(w9);
		HorizontalWall w10 = new HorizontalWall(5f, 1.25f, -1.25f, e);
		e.add(w10);
		
		//Right wall
		HorizontalWall w13 = new HorizontalWall(-5f, 3.5f, 5.0f, e);
		e.add(w13);
		HorizontalWall w14 = new HorizontalWall(-5f, -3.5f, -5.0f, e);
		e.add(w14);
		HorizontalWall w15 = new HorizontalWall(-5f, 1.25f, -1.25f, e);
		e.add(w15);
		
		//Top and bottom Vertical walls
		VerticalWall w11 = new VerticalWall(5.0f, -5.0f, 5.0f, e);
		e.add(w11);
		VerticalWall w12 = new VerticalWall(-5f, -5.0f, 5.0f, e);
		e.add(w12);
		
		//Vertical walls
		VerticalWall w16 = new VerticalWall(0f, 3.5f, 5.0f, e);
		e.add(w16);
		VerticalWall w17 = new VerticalWall(0f, -3.5f, -5.0f, e);
		e.add(w17);
		VerticalWall w18 = new VerticalWall(0f, 1.25f, -1.25f, e);
		e.add(w18);
		
		
		
		
	}
}
