// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package g16_tda593;

import simbad.sim.Boundary;
import simbad.sim.EnvironmentDescription;
import simbad.sim.HorizontalBoundary;
import simbad.sim.VerticalBoundary;

public class EnvironmentFactory {
	public Area makeEnvironment(String room) {
		if(room.equals("assignment3")) return new AssignmentRoom3().makeRoom();
		return null;
	}
	
};
