// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package g16_tda593;
public class Environment {
	/**
	 * 
	 */
	Area area; 
	
	public Environment (Area area) {
		this.area = area;
	}
	
	public Area getArea() {
		return area;
	}
	public void setArea(Area area) {
		this.area = area;
	}
};
