// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package g16_tda593;

import java.util.ArrayList;
import java.util.List;

import simbad.sim.EnvironmentDescription;

/************************************************************/
/**
 * 
 */
public class Environment extends EnvironmentDescription {
	/**
	 * 
	 */
	private List <Area> areas = new ArrayList<Area>();

	/**
	 * 
	 * @return 
	 */
	public List<Area> getAreas() {
		return areas;
	}
	public void addRoom(EnvironmentDescription e) {
		super.add(e);
	}
};
