// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package g16_tda593;

import java.util.Set;

import g16_tda593.Robot;
import g16_tda593.View;

/************************************************************/
/**
 * 
 */
public class GUI implements View {

	@Override
	public void updateRobots(Set<Robot> robots) {
		// TODO Auto-generated method stub
		
	}
};
