// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package g16_tda593;

import g16_tda593.Area;
import g16_tda593.Span;
import simbad.sim.EnvironmentDescription;

/************************************************************/
/**
 * 
 */
public class LogicalArea extends Area {
	public LogicalArea(Span span, int reward) {
		super(span, reward);
	}

	/**
	 * 
	 * @return 
	 */
	public EnvironmentDescription getEnvironment() {
		return super.getEnvironment();
	}

	/**
	 * 
	 * @return 
	 */
	public Span getSpan() {
		return super.getSpan();
	}
};
