// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package g16_tda593;

import simbad.sim.EnvironmentDescription;
import simbad.sim.HorizontalWall;
import simbad.sim.VerticalWall;

/************************************************************/
/**
 * 
 */
public class PhysicalArea extends Area {
	public PhysicalArea(Span span) {
		super(span);
	}

	public PhysicalArea(float f, float g, float h, float i) {
		super(f,g,h,i);
	}

	/**
	 * 
	 * @param a starting position of wall
	 * @param b Width/height (i don't really get it either)
	 * @param c Width/height (i don't really get it either)
	 * @param direction Specifies if the wall is horizontal (h) or vertical (v) if not specified it defaults to v.
	 */
	public void addWall(float a, float b, float c, char direction) {
		if(direction == 'h') {
			e.add(new HorizontalWall(a,b,c,e));
		}else {
			e.add(new VerticalWall(a,b,c,e));
		}
	}

	/**
	 * 
	 * @return 
	 */
	public EnvironmentDescription getEnvironment() {
		return super.getEnvironment();
	}

	/**
	 * 
	 * @return 
	 */
	public Span getSpan() {
		return super.getSpan();
	}
};
