// --------------------------------------------------------
// Code generated by Papyrus Java
package g16_tda593;

import project.Point;

public class PhysicalArea extends Area {
  public PhysicalArea(Point center, double radius) {
    super(center, radius);
  }
}
