// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package g16_tda593;

import java.util.List;
import java.util.Set;
import java.util.TimerTask;

/************************************************************/
/**
 * 
 */
public class RewardSystem extends TimerTask {
	/**
	 * 
	 */
	private int rewardPoint;
	/**
	 * 
	 */
	private boolean procedureA;

	/**
	 * 
	 * @param procedure 
	 */
	private void setProcedure(boolean procedure) {
		procedureA = procedure;
	}

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoint() {
		return this.rewardPoint;
	}
	public void setRewardPoint(int i) {
		rewardPoint = i;
	}
	public boolean getProcedure() {
		return procedureA;
	}
	@Override
	public void run() {
		System.out.println("Current rewardpoints are: " + getRewardPoint());
		System.out.println("Rewardpoints is running procedure A: " + procedureA);
	}
};
