// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package g16_tda593;

import java.util.List;
import project.AbstractRobotSimulator;
import project.Point;
import g16_tda593.Mission;
import g16_tda593.Sensors;

/************************************************************/
/**
 * 
 */
public class Robot extends AbstractRobotSimulator {
	
	public Robot(Point position, String name) {
		super(position, name);
		// TODO Auto-generated constructor stub
	}

	/**
	 * 
	 */
	private List<Sensors> sensors;
	/**
	 * 
	 */
	private Mission mission;
	/**
	 * 
	 */
	private String robotId;
	/**
	 * 
	 */
	private int missionPosition;

	/**
	 * 
	 * @return 
	 */
	public String getId() {
		return this.robotId;
	}

	/**
	 * 
	 * @return 
	 */
	public List<Sensors> getSensors() {
		return this.sensors;
	}

	/**
	 * 
	 * @return 
	 */
	public Mission getMission() {
		return this.mission;
	}

	/**
	 * 
	 * @return 
	 */
	public int getMissionPosition() {
		return this.missionPosition;
	}
};
