// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package g16_tda593;

import java.util.List;
import java.util.Timer;
import project.AbstractRobotSimulator;
import project.Point;
import g16_tda593.Mission;
import g16_tda593.Sensors;

/************************************************************/
/**
 * 
 */
public class RobotAvatar extends AbstractRobotSimulator {
	
	public RobotAvatar(Point position, String name) {
		super(position, name);
		// TODO Auto-generated constructor stub
		this.gps = new GPS();
		robotId = name;
		this.strategy = null;
	}
	
	public RobotAvatar(Point position, String name, Strategy strategy) {
		super(position, name);
		// TODO Auto-generated constructor stub
		this.gps = new GPS();
		robotId = name;
		this.strategy = strategy;
	}
	
	private GPS gps;
	/**
	 * 
	 */
	private List<Sensors> sensors;
	/**
	 * 
	 */
	private Mission mission;
	/**
	 * 
	 */
	private String robotId;
	/**
	 * 
	 */
	private Strategy strategy;
	/**
	 * 
	 * @return 
	 */
	public String getId() {
		return this.robotId;
	}

	/**
	 * 
	 * @return 
	 */
	public List<Sensors> getSensors() {
		return this.sensors;
	}
	
	public GPS getGPS() {
		return this.gps;
	}

	/**
	 * 
	 * @return 
	 */
	public Mission getMission() {
		return this.mission;
	}

	/**
	 * 
	 * @return 
	 */
	public Point getMissionPosition() {
		return this.gps.getValue();
	}
	
	public Strategy getStrategy() {
		return this.strategy;
	}
	
	public void setMission(Mission m) {
		System.out.println("Mission added to robot: " + robotId);
		this.mission = m;
	}
};
