// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package g16_tda593;
import g16_tda593.View;

/************************************************************/
/**
 * 
 */
public class TextOutput implements View {
	//This class outputs fun things in terminal.
	public void printReward(int reward, boolean procedure) {
		String output = "Pocedure: " + (procedure ? "A!" : "B!");
		System.out.println("Current reward points: " + reward + "\n" + output);
	}
	public void printRobotAdded(String robotID) {
		System.out.println("Ready for action! - Robot: " + robotID);
	}
	public void printCompletedMission(String robotID) {
		System.out.println("Rover to base! Rover to base! Mission completed! - Robot: " + robotID);
	}

};
