// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package g16_tda593;

import java.util.Set;

import g16_tda593.Controller;
import g16_tda593.Robot;

/************************************************************/
/**
 * 
 */
public interface View {
	/**
	 * 
	 */
	/*public Controller controller;
	/**
	 * 
	 */
	/*public int rewardPoints;
	/**
	 * 
	 * @param robots 
	 */
	public void updateRobots(Set<Robot> robots);
};
