// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classdiagram.mvc;

import classdiagram.mvc.Span;

/************************************************************/
/**
 * 
 */
public abstract class Area {
	/**
	 * 
	 */
	private Span span;
	/**
	 * 
	 */
	private undefined environmentDescription;

	/**
	 * 
	 * @return 
	 */
	public void getEnvironment() {
	}

	/**
	 * 
	 * @return 
	 */
	public Span getSpan() {
	}
};
