// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classdiagram.mvc;

import classdiagram.mvc.Environment;
import classdiagram.mvc.Mission;
import classdiagram.mvc.RewardSystem;
import classdiagram.mvc.Robot;
import classdiagram.mvc.View;

/************************************************************/
/**
 * 
 */
public class Controller {
	/**
	 * 
	 */
	private View[] views;
	/**
	 * 
	 */
	private Mission[] missions;
	/**
	 * 
	 */
	private Robot[] robots;
	/**
	 * 
	 */
	private undefined[] locControllers;
	/**
	 * 
	 */
	private Environment e;
	/**
	 * 
	 */
	private RewardSystem rs;
	/**
	 * 
	 */
	public Mission[] mission;
	/**
	 * 
	 */
	public RewardSystem rewardsystem;
	/**
	 * 
	 */
	public Environment environment;
	/**
	 * 
	 */
	public Robot[] robot;

	/**
	 * 
	 * @param robot 
	 */
	public void executeMission(Robot robot) {
	}

	/**
	 * 
	 * @param view 
	 */
	public void registerView(View view) {
	}

	/**
	 * for each v in views, v.updateRobots(robots)
	 */
	public void notify() {
	}

	/**
	 * 
	 * @param m 
	 * @param r 
	 */
	public void addMission(Mission m, Robot r) {
	}

	/**
	 * 
	 * @param r 
	 */
	public void removeMission(Robot r) {
	}

	/**
	 * 
	 */
	public void stopEverything() {
	}
};
