// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classdiagram.mvc;

import classdiagram.mvc.Area;

/************************************************************/
/**
 * 
 */
public class Environment {
	/**
	 * 
	 */
	private undefined[] areas;
	/**
	 * 
	 */
	public Area area;

	/**
	 * 
	 * @return 
	 */
	public void getAreas() {
	}
};
