// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classdiagram.mvc;

import classdiagram.mvc.Sensors;

/************************************************************/
/**
 * 
 */
public class GPS implements Sensors {
	/**
	 * 
	 */
	private float[] value;
};
