// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classdiagram.mvc;

import classdiagram.mvc.Robot;
import classdiagram.mvc.View;

/************************************************************/
/**
 * 
 */
public class GUI implements View {
	/**
	 * 
	 * @param robots 
	 */
	public void updateRobots(Robot robots) {
	}

	/**
	 * 
	 * @param robots 
	 */
	public void updateRobots(Robot robots) {
	}

	/**
	 * 
	 * @param robots 
	 */
	public void updateRobots(Robot robots) {
	}
};
