// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classdiagram.mvc;

import classdiagram.mvc.Area;
import classdiagram.mvc.Span;

/************************************************************/
/**
 * 
 */
public class LogicalArea {
	/**
	 * 
	 * @return 
	 */
	public void getEnvironment() {
	}

	/**
	 * 
	 * @return 
	 */
	public Span getSpan() {
	}
};
