// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classdiagram.mvc;

/************************************************************/
/**
 * 
 */
public class Mission {
	/**
	 * 
	 */
	private int[] point;
	/**
	 * 
	 */
	private int missionId;

	/**
	 * 
	 * @return 
	 */
	public int[] getPoints() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getId() {
	}
};
