// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classdiagram.mvc;

import classdiagram.mvc.Area;
import classdiagram.mvc.Span;

/************************************************************/
/**
 * 
 */
public class PhysicalArea {
	/**
	 * 
	 * @param a 
	 * @param b 
	 * @param c 
	 */
	public void addWall(float a, float b, float c) {
	}

	/**
	 * 
	 * @return 
	 */
	public void getEnvironment() {
	}

	/**
	 * 
	 * @return 
	 */
	public Span getSpan() {
	}
};
