// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classdiagram.mvc;

/************************************************************/
/**
 * 
 */
public class RewardSystem {
	/**
	 * 
	 */
	private int rewardPoint;
	/**
	 * 
	 */
	private boolean procedureA;

	/**
	 * 
	 * @param procedure 
	 */
	private void setProcedure(boolean procedure) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoint() {
	}
};
