// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classdiagram.mvc;

import classdiagram.mvc.Mission;
import classdiagram.mvc.Sensors;

/************************************************************/
/**
 * 
 */
public class Robot {
	/**
	 * 
	 */
	private Sensors[] sensors;
	/**
	 * 
	 */
	private Mission mission;
	/**
	 * 
	 */
	private int robotId;
	/**
	 * 
	 */
	private int missionPosition;
	/**
	 * 
	 */
	public Mission mission;
	/**
	 * 
	 */
	public Sensors[] sensors;

	/**
	 * 
	 * @return 
	 */
	public int getId() {
	}

	/**
	 * 
	 * @return 
	 */
	public Sensors[] getSensors() {
	}

	/**
	 * 
	 * @return 
	 */
	public Mission getMission() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getMissionPosition() {
	}
};
