// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classdiagram.mvc;

/************************************************************/
/**
 * 
 */
public interface Sensors {
	/**
	 * 
	 * @return 
	 */
	public classdiagram.mvc.Sensors[] getValue();
};
