// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classdiagram.mvc;

/************************************************************/
/**
 * 
 */
public class Span {
	/**
	 * 
	 */
	private double x;
	/**
	 * 
	 */
	private double y;
	/**
	 * 
	 */
	private double z;
	/**
	 * 
	 */
	private double w;

	/**
	 * 
	 * @return 
	 */
	public double getX() {
	}

	/**
	 * 
	 * @return 
	 */
	public double getY() {
	}

	/**
	 * 
	 * @return 
	 */
	public double getZ() {
	}

	/**
	 * 
	 * @return 
	 */
	public double getW() {
	}
};
