// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package classdiagram.mvc;

import classdiagram.mvc.Controller;
import classdiagram.mvc.Robot;

/************************************************************/
/**
 * 
 */
public interface View {
	/**
	 * 
	 */
	public Controller controller;
	/**
	 * 
	 */
	public int rewardPoints;

	/**
	 * 
	 * @param robots 
	 */
	public void updateRobots(Robot[] robots);
};
