// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package old;

import simbad.sim.EnvironmentDescription;

/************************************************************/
/**
 * 
 */
public abstract class Area {
	
	private int pointsRewarded;
	private int id;
	
	public Area(Span span, int reward) {
		this.span = span;
		this.pointsRewarded = reward;
	}
	
	public Area(float x1, float y1, float x2, float y2, int reward, int id) {
		this.span = new Span(x1,y1,x2,y2);
		this.pointsRewarded = reward;
		this.id = id;
	}
	
	public int getReward() {
		return pointsRewarded;
	}

	/**
	 * 
	 */
	private EnvironmentDescription e = new EnvironmentDescription();
	/**
	 * 
	 */
	private Span span;

	/**
	 * 
	 * @return 
	 */
	public EnvironmentDescription getEnvironment() {
		return e;
	}

	/**
	 * 
	 * @return 
	 */
	public Span getSpan() {
		return span;
	}
	
	public boolean containsRobot(RobotAvatar r) {
		if((r.getPosition().getX() >= span.x && r.getPosition().getX() <= span.x + span.height) &&
				(r.getPosition().getZ() >= span.y && r.getPosition().getZ() <= span.y + span.width)){
			//System.out.println("Robot " + r.getId() + " is in room " + id);
			return true;
		}
		return false;
	}
	
	public int getId() {
		return this.id;
	}
};
