// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package old;

import java.util.Set;

import old.RobotAvatar;
import old.View;

/************************************************************/
/**
 * 
 */
public class GUI implements View {

	@Override
	public void updateRobots(Set<RobotAvatar> robots) {
		// TODO Auto-generated method stub
		
	}
};
