// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package old;

import old.Area;
import old.Span;
import simbad.sim.EnvironmentDescription;

/************************************************************/
/**
 * 
 */
public class LogicalArea extends Area {
	public LogicalArea(Span span, int reward) {
		super(span, reward);
	}

	public LogicalArea(float f, float g, float h, float i, int reward, int id) {
		super(f,g,h,i, reward, id);
	}
	/**
	 * 
	 * @return 
	 */
	public EnvironmentDescription getEnvironment() {
		return super.getEnvironment();
	}

	/**
	 * 
	 * @return 
	 */
	public Span getSpan() {
		return super.getSpan();
	}
};
