// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package old;

import java.util.List;
import java.util.Set;
import java.util.TimerTask;

/************************************************************/
/**
 * 
 */
public class RewardSystem extends TimerTask {
	private List<Area> areas;
	private Set<RobotAvatar> robots;
	
	public RewardSystem(List<Area> areas, Set<RobotAvatar> robots) {
		this.areas = areas;
		this.robots = robots;
	}
	
	/**
	 * 
	 */
	private int rewardPoint;
	/**
	 * 
	 */
	private boolean procedureA;

	/**
	 * 
	 * @param procedure 
	 */
	private void setProcedure(boolean procedure) {
		procedureA = procedure;
	}

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoint() {
		return this.rewardPoint;
	}
	
	private void calculatePoints() {
		System.out.println("is it an empty list of areas? " + areas.size());
		for(Area a : areas) {
			if(a instanceof PhysicalArea && procedureA) {
				for(RobotAvatar r : robots) {
					if(a.containsRobot(r)) {
						rewardPoint = rewardPoint + a.getReward();
					}
				}
			} else if(a instanceof LogicalArea && !procedureA) {
				for(RobotAvatar r : robots) {
					if(a.containsRobot(r)) {
						rewardPoint = rewardPoint + a.getReward();
					}
				}
			}	
		}
	}

	@Override
	public void run() {
		calculatePoints();
		System.out.println("Current rewardpoints are: " + getRewardPoint());
		setProcedure(!procedureA);
		System.out.println("Rewardpoints is running procedure A: " + procedureA);
	}
};
