// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package old;

import java.util.ArrayList;
import java.util.List;
import java.util.Timer;

import old.Mission;
import old.Sensors;
import project.AbstractRobotSimulator;
import project.Point;

/************************************************************/
/**
 * 
 */
public class RobotAvatar extends AbstractRobotSimulator {

	
	public RobotAvatar(Point position, String name) {
		super(position, name);
		sensors.add(new GPS());
		robotId = name;
		this.strategy = null;
	}
	
	public RobotAvatar(Point position, String name, Strategy strategy) {
		super(position, name);
		this.sensors.add(new GPS());
		robotId = name;
		this.strategy = strategy;
	}
	
	private Area currentArea;
	
	/**
	 * 
	 */
	private List<Sensors> sensors = new ArrayList<Sensors>();
	/**
	 * 
	 */
	private Mission mission;
	/**
	 * 
	 */
	private String robotId;
	/**
	 * 
	 */
	private Strategy strategy;
	/**
	 * 
	 * @return 
	 */
	public String getId() {
		return this.robotId;
	}

	/**
	 * 
	 * @return 
	 */
	public List<Sensors> getSensors() {
		return this.sensors;
	}
	
	public GPS getGPS() {
		for(Sensors s : sensors) {
			if(s instanceof GPS) return (GPS) s;
		}
		return null;
	}

	/**
	 * 
	 * @return 
	 */
	public Mission getMission() {
		return this.mission;
	}

	/**
	 * 
	 * @return 
	 */
	public Point getMissionPosition() {
		return getGPS().getValue();
	}
	
	public Strategy getStrategy() {
		return this.strategy;
	}
	
	public void setMission(Mission m) {
		System.out.println("Mission added to robot: " + robotId);
		this.mission = m;
	}
	
	public void setCurrentArea(Area a) {
		this.currentArea = a;
	}
	
	public Area getCurrentArea() {
		return this.currentArea;
	}
};
