// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package old;

import project.Point;

/************************************************************/
/**
 * 
 */
public interface Sensors {
	/**
	 * 
	 * @return 
	 */
	public Point getValue();
};
