// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package old;

import java.util.Set;

import old.Controller;
import old.RobotAvatar;

/************************************************************/
/**
 * 
 */
public interface View {
	/**
	 * 
	 */
	/*public Controller controller;
	/**
	 * 
	 */
	/*public int rewardPoints;
	/**
	 * 
	 * @param robots 
	 */
	public void updateRobots(Set<RobotAvatar> robots);
};
